# Generated by Django 4.1.2 on 2022-10-08 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eurocode', models.CharField(max_length=30, verbose_name='Eurocode')),
                ('pavadinimas', models.CharField(max_length=50, verbose_name='Modelis')),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kaina, Eur')),
                ('aprasymas', models.TextField(max_length=300, verbose_name='Sudėtis')),
                ('update', models.DateField(auto_now_add=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorijos',
            },
        ),
        migrations.CreateModel(
            name='Likutis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(default=0, verbose_name='Likutis')),
            ],
            options={
                'verbose_name': 'Likutis',
                'verbose_name_plural': 'Likučiai',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzsakymo_laikas', models.DateField(auto_now_add=True)),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Užsakymo įvykdymo data')),
                ('status', models.CharField(blank=True, choices=[('a', 'Apdorojama'), ('g', 'Galima paimti'), ('l', 'Įvykdyta')], default='a', help_text='statusas', max_length=1)),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos', to='myorder.auto')),
                ('auto_tipas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='myorder.kategorija')),
                ('pirkejas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Iveskite prekės kiekį', verbose_name='Prekės kiekis')),
                ('auto_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_item', to='myorder.auto')),
                ('uzsakymas_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myorder.uzsakymas')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'Užsakymo eilutės',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='kategorija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategorijos', to='myorder.kategorija'),
        ),
        migrations.AddField(
            model_name='auto',
            name='lik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_link', to='myorder.likutis'),
        ),
    ]
