# Generated by Django 4.1.2 on 2022-10-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='auto_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_items', to='myorder.auto'),
        ),
    ]
