# Generated by Django 4.1.2 on 2022-10-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0004_profilis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name_plural': 'Profilis'},
        ),
    ]
